name: Bug Report
description: Report for broken or incorrect behaviour
labels: unconfirmed bug
body:
  - type: textarea
    attributes:
      label: Bug Summary
      description: Summerize your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
        What you did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please confirm that you have done the following checks!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
